# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdf11a4cb3155691d83e9d75b095b571a19dc47190c0a5ef0945864e885f3e1d7c04146643ca6bb0f984131b4eec48e8eaae819f0b0f78200de49c21896422d2

test:
  secret_key_base: 9c51f32cdd3b3a06ed22dbfb98c6f6f70c2850b3f59e5d42a1f4a1fcfd36d9011d36f84b8be87c70ebed4222ef3ade20ed2b0f0a126e8511b498cc674e6de7ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
